// <auto-generated />
namespace App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Inserindo_telefone2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inserindo_telefone2));
        
        string IMigrationMetadata.Id
        {
            get { return "202003042128567_Inserindo_telefone2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
